//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMatricula
    {
        public int IIDMATRICULA { get; set; }
        public int IIDCURSO { get; set; }
        public Nullable<decimal> NOTA1 { get; set; }
        public Nullable<decimal> NOTA2 { get; set; }
        public Nullable<decimal> NOTA3 { get; set; }
        public Nullable<decimal> NOTA4 { get; set; }
        public Nullable<decimal> PROMEDIO { get; set; }
        public Nullable<int> bhabilitado { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Matricula Matricula { get; set; }
    }
}
