//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matricula()
        {
            this.DetalleMatricula = new HashSet<DetalleMatricula>();
        }
    
        public int IIDMATRICULA { get; set; }
        public Nullable<int> IIDPERIODO { get; set; }
        public Nullable<int> IIDGRADO { get; set; }
        public Nullable<int> IIDSECCION { get; set; }
        public Nullable<int> IIDALUMNO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMatricula> DetalleMatricula { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
